### ISSUE TITLE
GetFileInfoFromRequest 有问题吧

### ISSUE THREAD

**Issue by lsd908321** [wangpengxpy/WebAPiResumeDownload#1]
/// <summary>
        /// 根据请求信息赋予封装的文件信息类
        /// </summary>
        /// <param name="request"></param>
        /// <param name="entityLength"></param>
        /// <returns></returns>
        private static FileInfo GetFileInfoFromRequest(HttpRequestMessage request, long entityLength)
        {
            var fileInfo = new FileInfo
            {
                From = 0,
                To = entityLength - 1,
                IsPartial = false,
                Length = entityLength
            };
            var rangeHeader = request.Headers.Range;
            if (rangeHeader == null || rangeHeader.Ranges.Count == 0) return fileInfo;
            if (rangeHeader.Ranges.Count > 1)
            {
                throw new HttpResponseException(HttpStatusCode.RequestedRangeNotSatisfiable);
            }
            var range = rangeHeader.Ranges.First();
            if (range.From.HasValue && range.From < 0 || range.To.HasValue && range.To > entityLength - 1)
            {
                throw new HttpResponseException(HttpStatusCode.RequestedRangeNotSatisfiable);
            }
            fileInfo.From = range.From ?? 0;
            fileInfo.To = range.To ?? entityLength - 1;
            fileInfo.IsPartial = true;
            fileInfo.Length = entityLength;
            if (range.From.HasValue && range.To.HasValue)
            {
                fileInfo.Length = range.To.Value - range.From.Value + 1;
            }
            else if (range.From.HasValue)
            {
                //fileInfo.Length = entityLength - range.From.Value + 1;
                //不需要+1，否则客户端下载成功但会一直阻塞
                fileInfo.Length = entityLength - range.From.Value;
            }
            else if (range.To.HasValue)
            {
                fileInfo.Length = range.To.Value + 1;
            }
            fileInfo.IsPartial = (fileInfo.Length != entityLength);
            return fileInfo;
        }

**Comment by wangpengxpy** [comment]
还有这问题，测试时未发现这个问题！
